-   id: flake9
    name: flake9
    description: '`flake9` is a command-line utility for enforcing style consistency across Python projects.'
    entry: flake9
    language: python
    types: [python]
    require_serial: true
